#:schema node_modules/wrangler/config-schema.json
name = "personal-website"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
NODE_VERSION = "18.18.0"